import SideNavbar from "@/components/admin/SideNavbar";

export const metadata = {
  title: "IndieStreet Admin",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <main className="flex max-w-[100rem] mx-auto">
      <SideNavbar />
      {children}
    </main>
  );
}
